/* This file was generated by SableCC (http://www.sablecc.org/). */

package baz.syntax.node;

import baz.syntax.analysis.*;

@SuppressWarnings("nls")
public final class AModFactor extends PFactor
{
    private PFactor _left_;
    private TPercent _percent_;
    private PUnary _right_;

    public AModFactor()
    {
        // Constructor
    }

    public AModFactor(
        @SuppressWarnings("hiding") PFactor _left_,
        @SuppressWarnings("hiding") TPercent _percent_,
        @SuppressWarnings("hiding") PUnary _right_)
    {
        // Constructor
        setLeft(_left_);

        setPercent(_percent_);

        setRight(_right_);

    }

    @Override
    public Object clone()
    {
        return new AModFactor(
            cloneNode(this._left_),
            cloneNode(this._percent_),
            cloneNode(this._right_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAModFactor(this);
    }

    public PFactor getLeft()
    {
        return this._left_;
    }

    public void setLeft(PFactor node)
    {
        if(this._left_ != null)
        {
            this._left_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._left_ = node;
    }

    public TPercent getPercent()
    {
        return this._percent_;
    }

    public void setPercent(TPercent node)
    {
        if(this._percent_ != null)
        {
            this._percent_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._percent_ = node;
    }

    public PUnary getRight()
    {
        return this._right_;
    }

    public void setRight(PUnary node)
    {
        if(this._right_ != null)
        {
            this._right_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._right_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._left_)
            + toString(this._percent_)
            + toString(this._right_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._left_ == child)
        {
            this._left_ = null;
            return;
        }

        if(this._percent_ == child)
        {
            this._percent_ = null;
            return;
        }

        if(this._right_ == child)
        {
            this._right_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._left_ == oldChild)
        {
            setLeft((PFactor) newChild);
            return;
        }

        if(this._percent_ == oldChild)
        {
            setPercent((TPercent) newChild);
            return;
        }

        if(this._right_ == oldChild)
        {
            setRight((PUnary) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
