/* This file was generated by SableCC (http://www.sablecc.org/). */

package baz.syntax.node;

import baz.syntax.analysis.*;

@SuppressWarnings("nls")
public final class ANegUnary extends PUnary
{
    private TMinus _minus_;
    private PUnary _unary_;

    public ANegUnary()
    {
        // Constructor
    }

    public ANegUnary(
        @SuppressWarnings("hiding") TMinus _minus_,
        @SuppressWarnings("hiding") PUnary _unary_)
    {
        // Constructor
        setMinus(_minus_);

        setUnary(_unary_);

    }

    @Override
    public Object clone()
    {
        return new ANegUnary(
            cloneNode(this._minus_),
            cloneNode(this._unary_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANegUnary(this);
    }

    public TMinus getMinus()
    {
        return this._minus_;
    }

    public void setMinus(TMinus node)
    {
        if(this._minus_ != null)
        {
            this._minus_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._minus_ = node;
    }

    public PUnary getUnary()
    {
        return this._unary_;
    }

    public void setUnary(PUnary node)
    {
        if(this._unary_ != null)
        {
            this._unary_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._unary_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._minus_)
            + toString(this._unary_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._minus_ == child)
        {
            this._minus_ = null;
            return;
        }

        if(this._unary_ == child)
        {
            this._unary_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._minus_ == oldChild)
        {
            setMinus((TMinus) newChild);
            return;
        }

        if(this._unary_ == oldChild)
        {
            setUnary((PUnary) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
