/* This file was generated by SableCC (http://www.sablecc.org/). */

package baz.syntax.node;

import baz.syntax.analysis.*;

@SuppressWarnings("nls")
public final class ANeqEquality extends PEquality
{
    private PEquality _left_;
    private TNeq _neq_;
    private PRelative _right_;

    public ANeqEquality()
    {
        // Constructor
    }

    public ANeqEquality(
        @SuppressWarnings("hiding") PEquality _left_,
        @SuppressWarnings("hiding") TNeq _neq_,
        @SuppressWarnings("hiding") PRelative _right_)
    {
        // Constructor
        setLeft(_left_);

        setNeq(_neq_);

        setRight(_right_);

    }

    @Override
    public Object clone()
    {
        return new ANeqEquality(
            cloneNode(this._left_),
            cloneNode(this._neq_),
            cloneNode(this._right_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANeqEquality(this);
    }

    public PEquality getLeft()
    {
        return this._left_;
    }

    public void setLeft(PEquality node)
    {
        if(this._left_ != null)
        {
            this._left_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._left_ = node;
    }

    public TNeq getNeq()
    {
        return this._neq_;
    }

    public void setNeq(TNeq node)
    {
        if(this._neq_ != null)
        {
            this._neq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._neq_ = node;
    }

    public PRelative getRight()
    {
        return this._right_;
    }

    public void setRight(PRelative node)
    {
        if(this._right_ != null)
        {
            this._right_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._right_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._left_)
            + toString(this._neq_)
            + toString(this._right_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._left_ == child)
        {
            this._left_ = null;
            return;
        }

        if(this._neq_ == child)
        {
            this._neq_ = null;
            return;
        }

        if(this._right_ == child)
        {
            this._right_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._left_ == oldChild)
        {
            setLeft((PEquality) newChild);
            return;
        }

        if(this._neq_ == oldChild)
        {
            setNeq((TNeq) newChild);
            return;
        }

        if(this._right_ == oldChild)
        {
            setRight((PRelative) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
