/* This file was generated by SableCC (http://www.sablecc.org/). */

package baz.syntax.node;

import baz.syntax.analysis.*;

@SuppressWarnings("nls")
public final class APosUnary extends PUnary
{
    private TPlus _plus_;
    private PUnary _unary_;

    public APosUnary()
    {
        // Constructor
    }

    public APosUnary(
        @SuppressWarnings("hiding") TPlus _plus_,
        @SuppressWarnings("hiding") PUnary _unary_)
    {
        // Constructor
        setPlus(_plus_);

        setUnary(_unary_);

    }

    @Override
    public Object clone()
    {
        return new APosUnary(
            cloneNode(this._plus_),
            cloneNode(this._unary_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPosUnary(this);
    }

    public TPlus getPlus()
    {
        return this._plus_;
    }

    public void setPlus(TPlus node)
    {
        if(this._plus_ != null)
        {
            this._plus_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._plus_ = node;
    }

    public PUnary getUnary()
    {
        return this._unary_;
    }

    public void setUnary(PUnary node)
    {
        if(this._unary_ != null)
        {
            this._unary_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._unary_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._plus_)
            + toString(this._unary_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._plus_ == child)
        {
            this._plus_ = null;
            return;
        }

        if(this._unary_ == child)
        {
            this._unary_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._plus_ == oldChild)
        {
            setPlus((TPlus) newChild);
            return;
        }

        if(this._unary_ == oldChild)
        {
            setUnary((PUnary) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
