/* This file was generated by SableCC (http://www.sablecc.org/). */

package baz.syntax.node;

import baz.syntax.analysis.*;

@SuppressWarnings("nls")
public final class ASimpleRelative extends PRelative
{
    private PAdditive _additive_;

    public ASimpleRelative()
    {
        // Constructor
    }

    public ASimpleRelative(
        @SuppressWarnings("hiding") PAdditive _additive_)
    {
        // Constructor
        setAdditive(_additive_);

    }

    @Override
    public Object clone()
    {
        return new ASimpleRelative(
            cloneNode(this._additive_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASimpleRelative(this);
    }

    public PAdditive getAdditive()
    {
        return this._additive_;
    }

    public void setAdditive(PAdditive node)
    {
        if(this._additive_ != null)
        {
            this._additive_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._additive_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._additive_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._additive_ == child)
        {
            this._additive_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._additive_ == oldChild)
        {
            setAdditive((PAdditive) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
