/* This file was generated by SableCC (http://www.sablecc.org/). */

package baz.syntax.node;

import baz.syntax.analysis.*;

@SuppressWarnings("nls")
public final class ASimpleEquality extends PEquality
{
    private PRelative _relative_;

    public ASimpleEquality()
    {
        // Constructor
    }

    public ASimpleEquality(
        @SuppressWarnings("hiding") PRelative _relative_)
    {
        // Constructor
        setRelative(_relative_);

    }

    @Override
    public Object clone()
    {
        return new ASimpleEquality(
            cloneNode(this._relative_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASimpleEquality(this);
    }

    public PRelative getRelative()
    {
        return this._relative_;
    }

    public void setRelative(PRelative node)
    {
        if(this._relative_ != null)
        {
            this._relative_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._relative_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._relative_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._relative_ == child)
        {
            this._relative_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._relative_ == oldChild)
        {
            setRelative((PRelative) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
