/* This file was generated by SableCC (http://www.sablecc.org/). */

package baz.syntax.node;

import baz.syntax.analysis.*;

@SuppressWarnings("nls")
public final class ASimpleExp extends PExp
{
    private PChoice _choice_;

    public ASimpleExp()
    {
        // Constructor
    }

    public ASimpleExp(
        @SuppressWarnings("hiding") PChoice _choice_)
    {
        // Constructor
        setChoice(_choice_);

    }

    @Override
    public Object clone()
    {
        return new ASimpleExp(
            cloneNode(this._choice_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASimpleExp(this);
    }

    public PChoice getChoice()
    {
        return this._choice_;
    }

    public void setChoice(PChoice node)
    {
        if(this._choice_ != null)
        {
            this._choice_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._choice_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._choice_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._choice_ == child)
        {
            this._choice_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._choice_ == oldChild)
        {
            setChoice((PChoice) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
