/* This file was generated by SableCC (http://www.sablecc.org/). */

package baz.syntax.node;

import baz.syntax.analysis.*;

@SuppressWarnings("nls")
public final class ASimpleConjunction extends PConjunction
{
    private PEquality _equality_;

    public ASimpleConjunction()
    {
        // Constructor
    }

    public ASimpleConjunction(
        @SuppressWarnings("hiding") PEquality _equality_)
    {
        // Constructor
        setEquality(_equality_);

    }

    @Override
    public Object clone()
    {
        return new ASimpleConjunction(
            cloneNode(this._equality_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASimpleConjunction(this);
    }

    public PEquality getEquality()
    {
        return this._equality_;
    }

    public void setEquality(PEquality node)
    {
        if(this._equality_ != null)
        {
            this._equality_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._equality_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._equality_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._equality_ == child)
        {
            this._equality_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._equality_ == oldChild)
        {
            setEquality((PEquality) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
